### ISSUE TITLE
Navigation bar is not fully-responsive .

### ISSUE THREAD

**Issue by amitmaindola** [sunilkrbajpai/resume#2]
### This can be fully responsive like that of Google (Screenshot Attatched)
![image](https://user-images.githubusercontent.com/79038241/135822090-9fff048f-db56-4f03-821b-5e9aa30dfbbb.png)

**Comment by amitmaindola** [comment]
I can work out this issue if you want me to.

**Comment by sunilkrbajpai** [comment]
ok do this

**Comment by amitmaindola** [comment]
@sunilkrbajpai  I have done that, now I am closing this issue.
